=== Zahco/sepa/src/main/resources/tp1.sepa.01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://univ.fr/sepa"
    xmlns="http://univ.fr/sepa">
    
    <xs:element name="CstmrDrctDbtInitn" type="rootType"/>
    
    <!-- Direct Debit Transaction Information -->
    <xs:element name="DrctDbtTxInf" type="ddtiType" />
    <!-- Direct Debit Transaction -->
    <xs:element name="DrctDbtTx" type="ddtType" />
    <!-- Debtor Agent -->
    <xs:element name="DbtrAgt" type="dAgentType" />
    <!-- Debtor -->
    <xs:element name="Dbtr" type="debtorType" />
    <!-- Debtor Account -->
    <xs:element name="DbtrAcct" type="dAccountType" />

    <xs:simpleType name="max35Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"></xs:minLength>
            <xs:maxLength value="35"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="IBANType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}[0-9]{2,2}[A-Z0-9]{1,30}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="BICType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{8,11}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    
	<xs:complexType name="InstdAmtType">
	  <xs:simpleContent>
	    <xs:extension base="xs:decimal">
	      <xs:attribute name="Ccy" use="required" type="xs:string">
	      </xs:attribute>
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="rootType">
	   <xs:sequence>
	       <xs:element ref="DrctDbtTxInf" minOccurs="1" maxOccurs="unbounded"/>
	   </xs:sequence>
	</xs:complexType>
	
    <xs:complexType name="ddtiType">
        <xs:sequence>
            <!-- Payment Information -->
            <xs:element name="PmtId" minOccurs="1" maxOccurs="1" type="max35Text"/>
            
            <!-- Instructed Amount -->
            <xs:element name="InstdAmt" minOccurs="1" maxOccurs="1" type="InstdAmtType"/>
            
            <xs:element ref="DrctDbtTx" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="DbtrAgt" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="Dbtr" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="DbtrAcct" minOccurs="1" maxOccurs="1"/>
            
            <!-- Remittance Information -->
            <xs:element name="RmtInf" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ddtType">
        <xs:sequence>
            <!--   Mandate Identifier -->
            <xs:element name="MndtId" minOccurs="1" maxOccurs="1" type="max35Text"/>
            <!-- Date of signature -->
            <xs:element name="DtOfSgntr" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dAgentType">
        <xs:choice>
            <xs:element name="BIC" minOccurs="1" maxOccurs="1" type="BICType"/>
            <xs:element name="Id" minOccurs="1" maxOccurs="1" type="max35Text"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="debtorType">
        <xs:sequence>
            <!-- Name -->
            <xs:element name="Nm" minOccurs="1" maxOccurs="1" type="max35Text"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dAccountType">
        <xs:choice>
            <xs:element name="IBAN" minOccurs="1" maxOccurs="1" type="IBANType"/>
            <!-- Private Identification -->
            <xs:element name="PrvtId" minOccurs="1" maxOccurs="1" type="max35Text"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== Zahco/sepa/src/main/resources/tp1.sepa.01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tp3.sepa-html.01.xsl"?>

<p:DrctDbtTxInf xmlns:p="http://univ.fr/sepa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/sepa tp1.sepa.01.xsd ">
  <PmtId>TEST#001</PmtId>
  <InstdAmt Ccy="EUR">321.05</InstdAmt>
  <p:DrctDbtTx>
    <MndtId>FF-57-E7</MndtId>
    <DtOfSgntr>2001-01-01</DtOfSgntr>
  </p:DrctDbtTx>
  <p:DbtrAgt>
    <BIC>DAEOFRPPCCT</BIC>
  </p:DbtrAgt>
  <p:Dbtr>
    <Nm>Mr Dupont</Nm>
  </p:Dbtr>
  <p:DbtrAcct>
    <IBAN>FE1405643596877A</IBAN>
  </p:DbtrAcct>
  <RmtInf>Ceci est un commentaire</RmtInf>
</p:DrctDbtTxInf>

=== Zahco/sepa/src/main/resources/tp1.sepa.011.xml
<?xml version="1.0" encoding="UTF-8"?>

<p:CstmrDrctDbtInitn xmlns:p="http://univ.fr/sepa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/sepa tp1.sepa.01.xsd ">
  <p:DrctDbtTxInf>
    <PmtId>TEST#001</PmtId>
    <InstdAmt Ccy="">1003.80</InstdAmt>
    <p:DrctDbtTx>
      <MndtId>FF-57-E7</MndtId>
      <DtOfSgntr>2001-01-01</DtOfSgntr>
    </p:DrctDbtTx>
    <p:DbtrAgt>
      <BIC>DAEOFRPPCCT</BIC>
    </p:DbtrAgt>
    <p:Dbtr>
      <Nm>Mr Dupont</Nm>
    </p:Dbtr>
    <p:DbtrAcct>
      <IBAN>FE1405643596877A</IBAN>
    </p:DbtrAcct>
    <RmtInf>Ceci est un commentaire</RmtInf>
  </p:DrctDbtTxInf>
  <p:DrctDbtTxInf>
    <PmtId>TEST#002</PmtId>
    <InstdAmt Ccy="">1004.80</InstdAmt>
    <p:DrctDbtTx>
      <MndtId>FF-57-E8</MndtId>
      <DtOfSgntr>2001-01-02</DtOfSgntr>
    </p:DrctDbtTx>
    <p:DbtrAgt>
      <BIC>DAEOFRPPCC</BIC>
    </p:DbtrAgt>
    <p:Dbtr>
      <Nm>Mme Dupont</Nm>
    </p:Dbtr>
    <p:DbtrAcct>
      <IBAN>FE1405643596877Z</IBAN>
    </p:DbtrAcct>
    <RmtInf>Ceci est un deuxi√®me commentaire</RmtInf>
  </p:DrctDbtTxInf>
</p:CstmrDrctDbtInitn>
